/gate/world/daughters/name defrise_box
/gate/world/daughters/insert box
/gate/defrise_box/placement/setTranslation 0.0 0.0 0.0 cm
/gate/defrise_box/geometry/setXLength 40. cm
/gate/defrise_box/geometry/setYLength 40. cm
/gate/defrise_box/geometry/setZLength 26.3 cm
/gate/defrise_box/setMaterial Air
/gate/defrise_box/vis/forceWireframe
/gate/defrise_box/vis/setColor gray

/gate/defrise_box/daughters/name VoxAttn
/gate/defrise_box/daughters/insert ImageNestedParametrisedVolume # Or ImageRegularParametrisedVolume
/gate/VoxAttn/geometry/setImage phantom/defrise/Defrise_Atn_200x200x200.h33
/gate/VoxAttn/geometry/setRangeToMaterialFile phantom/defrise/Attenuation_Defrise_Range.dat
/gate/VoxAttn/placement/setTranslation  0. 0. 0. cm
/gate/VoxAttn/attachPhantomSD

/gate/actor/addActor PhaseSpaceActor MyActor
/gate/actor/MyActor/save {root_fn}.psa.root
/gate/actor/MyActor/attachTo defrise_box
/gate/actor/MyActor/enableProductionVolume   false
/gate/actor/MyActor/enableProductionProcess  false
/gate/actor/MyActor/enableParticleName       false
/gate/actor/MyActor/enableWeight             false