/gate/world/daughters/name brain_box
/gate/world/daughters/insert box
/gate/brain_box/placement/setTranslation 0.0 0.0 0.0 cm
/gate/brain_box/geometry/setXLength 40. cm
/gate/brain_box/geometry/setYLength 40. cm
/gate/brain_box/geometry/setZLength 26.3 cm
/gate/brain_box/setMaterial Air
/gate/brain_box/vis/forceWireframe
/gate/brain_box/vis/setColor gray

/gate/brain_box/daughters/name VoxAttn
/gate/brain_box/daughters/insert ImageNestedParametrisedVolume # Or ImageRegularParametrisedVolume
/gate/VoxAttn/geometry/setImage phantom/brain_perf/Brain_Perfusion_Attn_72x90x77.h33
/gate/VoxAttn/geometry/setRangeToMaterialFile phantom/brain_perf/Attenuation_Brain_Range.dat
/gate/VoxAttn/placement/setTranslation  0. 0. 0. cm
/gate/VoxAttn/attachPhantomSD

#/gate/actor/addActor PhaseSpaceActor MyActor
#/gate/actor/MyActor/save {root_fn}.psa.root
#/gate/actor/MyActor/attachTo brain_box
#/gate/actor/MyActor/enableProductionVolume   false
#/gate/actor/MyActor/enableProductionProcess  false
#/gate/actor/MyActor/enableParticleName       false
#/gate/actor/MyActor/enableWeight             false
