/gate/source/addSource VoxSource voxel
/gate/source/VoxSource/reader/insert image
/gate/source/VoxSource/imageReader/translator/insert linear
/gate/source/VoxSource/imageReader/linearTranslator/setScale 3 becquerel #0.03 Bq
#/gate/source/VoxSource/imageReader/readFile source/fill_jaszczak/Fillable_Jaszczak_238x237x134_with_bkg.h33
/gate/source/VoxSource/imageReader/readFile source/fill_jaszczak/Fillable_Jaszczak_238x237x134_without_bkg.h33 #w/o background
/gate/source/VoxSource/imageReader/verbose 1
#/gate/source/VoxSource/gps/particle gamma
/gate/source/VoxSource/gps/particle e+
/gate/source/VoxSource/setForcedUnstableFlag true
/gate/source/VoxSource/gps/energytype Fluor18
/gate/source/VoxSource/setForcedHalfLife 6586 s
/gate/source/VoxSource/gps/ang/type iso
/gate/source/VoxSource/gps/ang/mintheta 0.0 deg
/gate/source/VoxSource/gps/ang/maxtheta 180.0 deg
/gate/source/VoxSource/gps/ang/minphi 0.0  deg
/gate/source/VoxSource/gps/ang/maxphi 360.0 deg
/gate/source/VoxSource/gps/energytype Mono
#/gate/source/VoxSource/gps/ene/mono 140.5 keV # For Tc-99m
/gate/source/VoxSource/setIntensity 1
/gate/source/VoxSource/setPosition -223.589814 -222.650361 -167.5 mm
/gate/source/VoxSource/dump 1