/gate/source/addSource twogamma 
/gate/source/twogamma/setActivity 5e4 becquerel 
/gate/source/twogamma/setType backtoback 

# POSITION 
/gate/source/twogamma/gps/centre 0 0 0 mm 

# PARTICLE 
/gate/source/twogamma/gps/particle gamma 
/gate/source/twogamma/gps/energytype Mono 
/gate/source/twogamma/gps/monoenergy 0.511 MeV 

# TYPE = Volume or Surface 
/gate/source/twogamma/gps/type Point 

# SET THE ANGULAR DISTRIBUTION OF EMISSION 
/gate/source/twogamma/gps/angtype iso 

# SET MIN AND MAX EMISSION ANGLES 
/gate/source/twogamma/gps/mintheta 0. deg 
/gate/source/twogamma/gps/maxtheta 180.0 deg 
/gate/source/twogamma/gps/minphi 0. deg 
/gate/source/twogamma/gps/maxphi 360.0 deg 

#/gate/source/twogamma/visualize 100000 green 2

/gate/source/list
