

#=====================================================
# CUTS
#=====================================================

/gate/physics/Gamma/SetCutInRegion      crystal 1.0 mm
/gate/physics/Electron/SetCutInRegion   crystal 1.0 mm
/gate/physics/Positron/SetCutInRegion   crystal 1.0 mm


#/gate/physics/Gamma/SetCutInRegion      phantom 0.1 mm
#/gate/physics/Electron/SetCutInRegion   phantom 0.1 mm
#/gate/physics/Positron/SetCutInRegion   phantom 0.1 mm

#/gate/physics/SetMaxStepSizeInRegion    phantom 0.01 mm

