
#=====================================================
#   D I G I T I Z E R: DETECTOR ELECTRONIC RESPONSE
#===================================================== 

/gate/digitizer/Singles/insert systemFilter
/gate/digitizer/Singles/systemFilter/selectSystem cylindricalPET

/gate/digitizer/Singles/insert adder
/gate/digitizer/Singles/insert readout
/gate/digitizer/Singles/readout/setDepth 2

/gate/digitizer/Singles/insert blurring
/gate/digitizer/Singles/blurring/setResolution 0.10
/gate/digitizer/Singles/blurring/setEnergyOfReference 511. keV

/gate/digitizer/Singles/insert thresholder
/gate/digitizer/Singles/thresholder/setThreshold 435. keV
/gate/digitizer/Singles/insert upholder
/gate/digitizer/Singles/upholder/setUphold 650. keV

/gate/digitizer/Singles/insert timeResolution
/gate/digitizer/Singles/timeResolution/setTimeResolution 0.151321 ns



#=====================================================
#	C O I N C I D E N C E    S O R T E R
#===================================================== 

# Regular coincidence sorter
/gate/digitizer/name Coincidences
/gate/digitizer/insert coincidenceSorter 
/gate/digitizer/Coincidences/setInputName Singles
/gate/digitizer/Coincidences/setWindow 4.5 ns
/gate/digitizer/Coincidences/MultiplesPolicy takeWinnerOfGoods

# Delayed coincidence sorter for random estimation
/gate/digitizer/name DelayedCoincidences
/gate/digitizer/insert coincidenceSorter
/gate/digitizer/DelayedCoincidences/setInputName Singles
/gate/digitizer/DelayedCoincidences/setWindow 4.5 ns
/gate/digitizer/DelayedCoincidences/setOffset 100 ns
/gate/digitizer/DelayedCoincidences/MultiplesPolicy takeWinnerOfGoods



